LOGDIR="./logs"
LOGFILE="$LOGDIR/monitor_system.log"

CPU_THRESHOLD=1 #Sets the CPU usage threshold to 1%. You can adjust this value later.
MEMORY_THRESHOLD=3 #Sets the MEMORY usage threshold to 3%. You can adjust this value later.
DISK_THRESHOLD=5 #Sets the DISK usage threshold to 5%. You can adjust this value later.

RED=$(tput setaf 1)
RESET=$(tput sgr0)

INTERVAL=10
